### ISSUE TITLE
首次访问如果使用的是中国大陆的 IP 会出现以下情况

### ISSUE THREAD

**Issue by Jeamorg** [jason5ng32/MyIP#10]
如图：
使用非中国大陆 IP 后布局恢复正常

![Snipaste_2023-12-02_11-44-40](https://github.com/jason5ng32/MyIP/assets/93057377/63b3f0ae-1b66-4723-8d54-a555acb79128)

**Comment by jason5ng32** [comment]
看起来是你当地的运营商访问 css和 js 资源时断开了。

**Comment by jason5ng32** [comment]
什么系统？Win 10？

**Comment by jason5ng32** [comment]
我换了一个 emoji，应该 win 10 也能显示了……吧

**Comment by jason5ng32** [comment]
> 如图： 使用非中国大陆 IP 后布局恢复正常
> 
> ![Snipaste_2023-12-02_11-44-40](https://private-user-images.githubusercontent.com/93057377/287418716-63b3f0ae-1b66-4723-8d54-a555acb79128.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MzM4MTYsIm5iZiI6MTcwMTUzMzUxNiwicGF0aCI6Ii85MzA1NzM3Ny8yODc0MTg3MTYtNjNiM2YwYWUtMWI2Ni00NzIzLThkNTQtYTU1NWFjYjc5MTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE2MTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZmYyNmU1ZjIzZjM0M2U4YmQxZGZlMTlhNTg5MDU0MzM5MDhkMTFjMTg1MzNiMTkwZTY0MTMwNzI0YjdjZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ru0Z1y7qe9z5FE70WzQRaUdIl0YTnfph1CB9QQbS93Y)

Improved with #11 .
