### ISSUE TITLE
[Feature Request] （根据网站显示的语言来）决定 Bing 地图 的语言

### ISSUE THREAD

**Issue by YaoSiQian** [jason5ng32/MyIP#12]
根据 [官方文档](https://learn.microsoft.com/en-us/bingmaps/rest-services/imagery/get-imagery-metadata#basic-metadata-url)，使用 Bing Map API 可以决定生成的图片的语言。

在本项目中，
https://github.com/jason5ng32/MyIP/blob/8f8c7332da65ba28611422919d7d83df46194334/res/app.js#L167
如果想显示简体中文的内容，就可以在请求链接后添加 [culture](https://learn.microsoft.com/zh-cn/bingmaps/rest-services/common-parameters-and-types/culture-parameter) 参数 `&c=zh-cn`。

~当然，原文档还为亲切的中国用户准备了个非常zzzq的 [userRegion](https://learn.microsoft.com/zh-cn/bingmaps/rest-services/common-parameters-and-types/user-context-parameters) 参数 `&ur=cn`，不好评价~

<details>
  <summary>例图</summary>
  
![简体中文](https://github.com/jason5ng32/MyIP/assets/29835749/9e3aaf43-9349-4f15-8607-5e2003956c7d "简体中文")

![简体中文，中国](https://github.com/jason5ng32/MyIP/assets/29835749/bfb6aa74-a1af-4b7a-b465-e11c80957364 "简体中文，中国")

</details>

**Comment by jason5ng32** [comment]
已增加。
