### ISSUE TITLE
自己部署的之后,使用右下角查询ip不准确问题

### ISSUE THREAD

**Issue by anduinnn** [jason5ng32/MyIP#125]
1.首先我使用自己部署的项目查询`118.249.21.169`  ,显示的是北京的ip
![image](https://github.com/jason5ng32/MyIP/assets/68073009/94860c7b-b940-48fa-a757-17c8df24c575)  
![image](https://github.com/jason5ng32/MyIP/assets/68073009/c82512a7-7245-4c35-afd6-becc8b22d979)

2. 使用 `https://ipcheck.ing/`查询`118.249.21.169`,却是准确的  
![image](https://github.com/jason5ng32/MyIP/assets/68073009/04ed70d8-0476-4a5c-898b-7f04c994aafa)  
![image](https://github.com/jason5ng32/MyIP/assets/68073009/af023b6b-5533-45e6-94e5-7841253089e9)  

我发现他们使用的请求接口不一样,自己部署的使用的是`/api/ipapicom`,而这个项目使用的是`/api/ipchecking`
在我跟进代码的时候发现使用这个接口需要`IPChecking_API_KEY`环境变量  
![image](https://github.com/jason5ng32/MyIP/assets/68073009/1888edc3-b0a9-4be9-8ec2-ad6826894fac)

3. ip查询不准确如何解决或者 `IPChecking_API_KEY`在哪里获取;
ps: 刚刚跟同事battle 因为查询的ip地址不准确丢大脸┭┮﹏┭┮

**Comment by jason5ng32** [comment]
哈哈哈，不好意思让你丢了一下脸……
api.ipcheck.ing 是我自己的后端服务，我还没完善好，所以没有开源。

**Comment by jason5ng32** [comment]
谢谢你，不过当下最关键的问题是，得有人赞助数据库，哈哈哈哈哈。国内的 IP 库对于开源项目来说，支付不起。
