### ISSUE TITLE
自己部署后,使用右下角查询 ip 不能用，返回 403

### ISSUE THREAD

**Issue by 80imike** [jason5ng32/MyIP#128]
自己部署的,使用右下角查询 ip 不能用，返回 403

<img width="1406" alt="image" src="https://github.com/jason5ng32/MyIP/assets/1665201/a13cea65-1132-46ce-904e-9da9f071eda1">

这是我部署的 https://ipinfo.ing/ 

大佬，有空看看是什么原因呢？ 

我记得之前的版本是可以正常用的，现在发现不能用了，是用的 docker 最新镜像

**Comment by jason5ng32** [comment]
这里确实有个 bug，在 #129 进行了修复。
但这个修复和你遇到的 403 应该无关，检查一下 apikey 是否正确或超限。

**Comment by 80imike** [comment]
> 这里确实有个 bug，在 #129 进行了修复。 但这个修复和你遇到的 403 应该无关，检查一下 apikey 是否正确或超限。

ip 查询这个功能现在还需要三方 apikey 吗？之前版本中没有单独配置过 apikey，是用的哪一个三方服务呢？
