### ISSUE TITLE
I hope to support iplook.io and add IP type display.

### ISSUE THREAD

**Issue by webees** [jason5ng32/MyIP#144]
# `iplook.io` has an IP threat database, which is particularly important for e-commerce operations when selecting IP addresses.

# Regarding the type of IP, it is desired to display `ISP `or `HOSTING `type.

**Comment by jason5ng32** [comment]
iplook.io's free plan does not contain IP type and threat datas.

**Comment by webees** [comment]
`ipinfo.io` supports ip types.

It would be really great if we could show more interface data.

![image](https://github.com/jason5ng32/MyIP/assets/5155291/72419003-f19f-476f-9b0b-0c50ceadb551)

**Comment by jason5ng32** [comment]
Not planned.
