### ISSUE TITLE
能否指导一下如果使用docker搭建这个项目？

### ISSUE THREAD

**Issue by brucelau1987cn** [jason5ng32/MyIP#15]
想使用docker搭建在自己的服务器上，想请教一下如何实现？感谢

**Comment by haotianlPM** [comment]
给大神们献丑了，你直接git clone文件夹到本机，做反向代理就可以了

**Comment by jason5ng32** [comment]
如此静态的程序，且不需要修改任何系统的配置……应该不至于要用 docker 吧亲……

**Comment by brucelau1987cn** [comment]
> 给大神们献丑了，你直接git clone文件夹到本机，做反向代理就可以了

怎么做 什么端口？

**Comment by haotianlPM** [comment]
> > 给大神们献丑了，你直接git clone文件夹到本机，做反向代理就可以了
> 
> 怎么做 什么端口？

nginx和caddy都可以，端口不限，类似你做个反向代理访问 这个文件夹就行。我用的npm，直接内网dns劫持，这样我就可以通过域名访问了（公网没部署，感觉没必要）

**Comment by haotianlPM** [comment]
> > 给大神们献丑了，你直接git clone文件夹到本机，做反向代理就可以了
> 
> 怎么做 什么端口？
npm参考，直接代理本地端口80，在高级中输入你的路径，参考以下
location / {
  root /data/MyIP;
}

**Comment by brucelau1987cn** [comment]
> > > 给大神们献丑了，你直接git clone文件夹到本机，做反向代理就可以了
> > 
> > 
> > 怎么做 什么端口？
> > npm参考，直接代理本地端口80，在高级中输入你的路径，参考以下
> > location / {
> > root /data/MyIP;
> > }

感谢解惑 我知道怎么处理了 我去测试一下 我搞个nginx处理一下

**Comment by brucelau1987cn** [comment]
> > > 给大神们献丑了，你直接git clone文件夹到本机，做反向代理就可以了
> > 
> > 
> > 怎么做 什么端口？
> > npm参考，直接代理本地端口80，在高级中输入你的路径，参考以下
> > location / {
> > root /data/MyIP;
> > }

感谢 已经用NPM反代本地静态网页成功 谢谢
需要在NPM项目的data文件里git clone下来 参照你的代码 直接运行成功 感谢

**Comment by NoverNobida** [comment]
@jason5ng32 这个的nginx有配置示例吗？在自行部署后，似乎有一定错误，导致请求 `https://domain.com/logo.svg` 变成了 `https://domain.com/api/logo.svg`
