### ISSUE TITLE
通过检查是否数据中心ip来判定vpn是否不准确并带有误导性

### ISSUE THREAD

**Issue by muink** [jason5ng32/MyIP#156]
我测试了几个阿里云的ip, 均判为vpn. 然而实际上他们都使用正常的国内网络
后来突发奇想测试了`223.5.5.5`, 依然判定为vpn
测的 azure 机器也是一样的, 判定为vpn

页面上对vpn的检查, 是否具有真实参考意义, 我持怀疑态度

**Comment by jason5ng32** [comment]
同意你的怀疑态度。
别说 VPN 判断了，就连 IP 段的判断都不一定是准确的。
