### ISSUE TITLE
可以进行docker的部署吗？

### ISSUE THREAD

**Issue by Hello-XPH** [jason5ng32/MyIP#17]

**Comment by brucelau1987cn** [comment]
刚刚又发现一个可以复刻的静态网站，不需要自己有VPS，有免费的100G流量 应该足够了
https://www.youtube.com/watch?v=2LqB5hkV3JQ
参考这个视频操作吧，免费且好用 哈哈哈，国内访问延迟25ms 堪比baidu.com

**Comment by jason5ng32** [comment]
提供 Docker 镜像： https://hub.docker.com/r/jason5ng32/myip

**Comment by Hello-XPH** [comment]
谢谢
