### ISSUE TITLE
再开：没法打开/关闭地图按钮的问题

### ISSUE THREAD

**Issue by dreamsmaner** [jason5ng32/MyIP#171]
作者你好，还是前几天那个没法打开/关闭地图按钮的问题，那个issue被你close了，但其实变量名我设置应该是对的，问题没解决。

              > 变量名是 BING_MAP_API_KEY 。

Docker里是写的BING_MAP_API_KEY，上面issue的描述没打全，看图。
![image](https://github.com/jason5ng32/MyIP/assets/42914674/251510d3-53c9-4557-8435-d80417d23a94)

_Originally posted by @dreamsmaner in https://github.com/jason5ng32/MyIP/issues/161#issuecomment-2049735341_

**Comment by jason5ng32** [comment]
帮不了你，程序是没问题的。我也通过 docker run 部署了一次，一切正常。建议部署后进入容器里看看环境变量是不是确实已经进去了。再不行，结合你的环境，问问 ChatGPT。

**Comment by dreamsmaner** [comment]
> `BING_MAP_API_KEY` 的值没有 `""` ？

加引号和不加引号我都试过了，都不行

**Comment by catfishlty** [comment]
有同样问题，但是系统变量是成功注入到容器中的。
具体原因是因为`/api/configs` API会校验`ALLOWED_DOMAINS`, 所以加上`ALLOWED_DOMAINS`就好了。

https://github.com/jason5ng32/MyIP/blob/8344159b3f60ca690d6bb3fa9f23ccf137a90088/api/configs.js#L8-L18

**Comment by jason5ng32** [comment]
应该不是这个原因。
allowedDomains 默认会加上 localhost ，即使环境变量不存在 ALLOWED_DOMAINS 也不会出错。
我在服务器上不带其它环境变量直接运行：

```
run -d -p 18966:18966 \
  -e BING_MAP_API_KEY="地图的 KEY" \
  --name myip \
  jason5ng32/myip:latest
```
  
  也是没有问题的。

**Comment by jason5ng32** [comment]
allowedDomains 默认会加上 localhost ，即使环境变量不存在 ALLOWED_DOMAINS 也不会出错。

不过你给了我楼主那个问题的思路（以及你也遇到这个问题的原因），可能我们访问群晖时用的不是 localhost ，而是具体的 IP 或者 DDNS 之后的域名。所以，如果不设置环境变量 ALLOWED_DOMAINS ，按照我的程序逻辑，地图就不会显示。

破案了。

**Comment by dreamsmaner** [comment]
测试成功，果然ALLOWED_DOMAINS加上群晖的IP就好了，谢谢 @catfishlty 和 @jason5ng32 。
