### ISSUE TITLE
关于[ IP检测] Emoji显示错误的BUG

### ISSUE THREAD

**Issue by WizisCool** [jason5ng32/MyIP#2]
已在我的博客中写出解决办法

1. `🛜 IP数据`显示错误

   ![image-20231127205625386](https://image.dooo.ng/i/2023/11/27/656491fa5cc1b.jpg)
   - 这应该是一个小Bug, 原作者是编写平台可能是MacOS,这是一个emoji表情
     但是在Windows平台上会显示一个小方块
   - 解决办法也很简单,在 `index.html` 中搜索 `IP 数据`  
     将  
     ```<h2 id="scrollspyHeading1" class="col-4" :class="{'mobile-h2' : isMobile }">🛜 IP 数据</h2>   ```  
     改为  
     ```<h2 id="scrollspyHeading1" class="col-4" :class="{'mobile-h2' : isMobile }"><i class="bi bi-radar"></i> IP 数据</h2>```   
     即可  
   - 现在IP数据被成了一个图标,该项目支持 [fontawesome](https://fontawesome.com/icons) 图标库, 你可以在这里找一个自己喜欢的图标替换掉 `bi bi-radar`
   - ![image-20231127205914651](https://image.dooo.ng/i/2023/11/27/656492a3b128d.jpg)  
   - 此问题已在Github向作者提交

**Comment by jason5ng32** [comment]
哈哈哈哈，对，我确实使用 macOS。
