### ISSUE TITLE
Impossible de récupérer les résultats de résolution

### ISSUE THREAD

**Issue by lmq8267** [jason5ng32/MyIP#201]
Docker self-deployment cannot resolve dns records, but it can be resolved using your website

**Comment by jason5ng32** [comment]
请按照 issue 模板，提供所有的 log，也请在提交 issue 之前，自行 Google 或 ChatGPT 一下。
否则，这就像「哥们，你帮我看看为什么我的电脑这么慢」，别人能帮你解决？

**Comment by lmq8267** [comment]
我是docker部署 命令是
docker run -d -p 18966:18966 --name myip --restart always jason5ng32/myip:latest
然后使用dns解析器，无论是A还是AAAA TXT都无法解析，你的网站可以解析。是需要添加什么环境变量才能使用dns解析器吗？

------------------ Original ------------------
From: Jason Ng ***@***.***&gt;
Date: Sun,May 5,2024 10:20 PM
To: jason5ng32/MyIP ***@***.***&gt;
Cc: lmq8267 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [jason5ng32/MyIP] Impossible de récupérer les résultats de résolution (Issue #201)





 
请按照 issue 模板，提供所有的 log，也请在提交 issue 之前，自行 Google 或 ChatGPT 一下。
 否则，这就像「哥们，你帮我看看为什么我的电脑这么慢」，别人能帮你解决？
