### ISSUE TITLE
“全球延迟测试”的显示 bug

### ISSUE THREAD

**Issue by Jeamorg** [jason5ng32/MyIP#202]
如图所示，延迟显示块不会消失，测试网站：https://ipcheck.ing

![Snipaste_2024-05-08_23-13-14](https://github.com/jason5ng32/MyIP/assets/93057377/43dce6be-1c82-45dc-bcd0-60f5493bed69)

![Snipaste_2024-05-08_23-11-43](https://github.com/jason5ng32/MyIP/assets/93057377/74d6f0bd-a0b0-4296-8976-d9453b3e4f3e)

**Comment by jason5ng32** [comment]
请按照 issue 模板，提供稳定复现步骤、环境和浏览器 log。
