### ISSUE TITLE
新增的 whois 功能查询报错

### ISSUE THREAD

**Issue by 80imike** [jason5ng32/MyIP#204]
新增的 whois 功能查询报错

<img width="761" alt="image" src="https://github.com/jason5ng32/MyIP/assets/1665201/f997b4a5-b3c0-43ac-acab-37309862edd6">

看了下报错，报的是 403 

<img width="648" alt="image" src="https://github.com/jason5ng32/MyIP/assets/1665201/ef7a9e5a-d3dc-43d8-be28-3465b0d5a5ed">

whois 调的 api 服务器是有限制吗？

**Comment by jason5ng32** [comment]
需要服务器环境本身支持 whois 命令。如果没有的话，可以自行手动安装一下。

**Comment by 80imike** [comment]
> 需要服务器环境本身支持 whois 命令。如果没有的话，可以自行手动安装一下。

服务器上是有 whois 命令的，但是用 docker 跑的 [MyIP](https://github.com/jason5ng32/MyIP) ，镜像就是 jason5ng32/myip:latest 是容器里需要 whois ?

**Comment by jason5ng32** [comment]
我测了一下，确实容器里已经自带了 whois ，不需要再手动安装。而我在本地测试，whois 信息是又返回的。
有没有一种可能是，你的服务器连不上 whois 查询的服务器们？

**Comment by 80imike** [comment]
> 我测了一下，确实容器里已经自带了 whois ，不需要再手动安装。而我在本地测试，whois 信息是又返回的。 有没有一种可能是，你的服务器连不上 whois 查询的服务器们？

<img width="956" alt="image" src="https://github.com/jason5ng32/MyIP/assets/1665201/b7d3d1c8-024e-4390-a346-bb694de3009b">

我在容器中直接执行 whois  666666.dev  是能正常返回的

**Comment by jason5ng32** [comment]
那我就不清楚了
