### ISSUE TITLE
希望增加几个功能

### ISSUE THREAD

**Issue by 2131411** [jason5ng32/MyIP#21]
IP质量检查：
https://www.ip123.in/#fraud_check
原生IP查询
https://bgp.he.net/
伪装度查询：
https://whoer.net/zh

**Comment by jason5ng32** [comment]
愚以为，这是都是伪概念。

所谓 IP 质量，实际上就是看这个 IP 对应的网站们在搜索引擎发排名，有没有被标记为欺诈之类的。但上述计算是基于域名的，域名和 IP 不是绑定不变的关系，因此所谓的 IP 质量并不靠谱。

所谓原生 IP，这个概念只不过是机场厂商解锁流媒体后给自己套的概念。

伪装度我倾向于认为是 VPN 厂商通过一些科学和不科学的检测后计算的值，然后忽悠人买它的服务。
