### ISSUE TITLE
run npm install卡住了

### ISSUE THREAD

**Issue by BigdataZjk** [jason5ng32/MyIP#224]
## Environment:

* Operating System: OpenCloudOS 9
* Browser (if applicable): Windows Edge
* Node Version:
* Vite Version:
* Vue3 Version:
* Docker Version (if applicable): 24.0.7
* Deployment Method (Vercel/Docker/Node):
* Environment Variables (without sensitive info):
* Any other relevant software versions:

## Description:

我运行docker命令来安装myip时，卡住不动了，具体操作如下：

``` bash
[root@VM-20-9-opencloudos myip-18966]# docker build -t myip:V704 .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon   1.42MB
Step 1/17 : FROM node:20-alpine as build-stage
 ---> fe8299495988
Step 2/17 : WORKDIR /app
 ---> Using cache
 ---> 74b6899bd5a5
Step 3/17 : COPY package*.json ./
 ---> Using cache
 ---> 71e2aa338a7a
Step 4/17 : RUN npm install
 ---> Running in 0f81a1aaec15
```

## Expected Behavior:

顺利生成镜像

## Actual Behavior:

Describe what actually happened. Include screenshots or screen recordings if possible.

## Terminal & Console Logs:

**Important**: Please include the terminal logs and browser console logs if applicable. These logs are crucial for identifying the root cause of the issue.

### Terminal Logs (include any error messages or stack traces):

[Logs here]

### Browser Console Logs (if frontend issue):

[Logs here]

Additional Context:

Add any other context about the problem here, like links to related issues, logs, etc.

## Possible Solution (optional):

我希望依赖包可以更人性化一点，不至于需要VPN才能获取到特定的依赖包

**Comment by jason5ng32** [comment]
中国政府干的网络审查让开发者来解决？有毛病。

**Comment by BigdataZjk** [comment]
为你产品提优化，你还真以为自己多牛逼呢，**脑残**就不要当开发者了，这么简单的东西还装起来了

**Comment by xwvike** [comment]
@BigdataZjk 我希望GFW人性化一点😁

**Comment by imPrk0** [comment]
> 为你产品提优化，你还真以为自己多牛逼呢，**脑残**就不要当开发者了，这么简单的东西还装起来了

你平时使用的源码，无论是前端后端什么语言，你安装依赖都很顺利吗？就这个项目不行吗？

自己安装依赖不好不会用 npmmirror.com 吗？

我们安装依赖怎么都没事，怎么就你有事呢？

自己的💩没舔干净怨开发者有什么用？

你安装依赖又不是从开发者的服务器

你应该骂 npm 包管理工具怎么就歧视你不让你正常访问

**Comment by LINGMOE-X** [comment]
@BigdataZjk 你呀，妥妥的小丑，你用npm，第一步你在国内不应该**改变镜像**吗，免费提供都不用。但凡有点脑子，人家npm包服务器是国外的。要不然你自己指定链接下载依赖嘞？自己编译那不更好。🤗

**Comment by BigdataZjk** [comment]
> @BigdataZjk 我希望GFW人性化一点😁

我倒是希望你妈妈更人性化

**Comment by BigdataZjk** [comment]
> > 为你产品提优化，你还真以为自己多牛逼呢，**脑残**就不要当开发者了，这么简单的东西还装起来了
> 
> 你平时使用的源码，无论是前端后端什么语言，你安装依赖都很顺利吗？就这个项目不行吗？
> 
> 自己安装依赖不好不会用 npmmirror.com 吗？
> 
> 我们安装依赖怎么都没事，怎么就你有事呢？
> 
> 自己的💩没舔干净怨开发者有什么用？
> 
> 你安装依赖又不是从开发者的服务器
> 
> 你应该骂 npm 包管理工具怎么就歧视你不让你正常访问

臭伪洋鬼子，就不要叫了，会不会用docker，npmmirror.com是你妈妈开的？可以注入依赖吗？

**Comment by BigdataZjk** [comment]
> @BigdataZjk 你呀，妥妥的小丑，你用npm，第一步你在国内不应该**改变镜像**吗，免费提供都不用。但凡有点脑子，人家npm包服务器是国外的。要不然你自己指定链接下载依赖嘞？自己编译那不更好。🤗

感觉自己啥都会，淘宝、腾讯、阿里镜像你试了吗？就赔着洋鬼子叫？

**Comment by imPrk0** [comment]
> > > 为你产品提优化，你还真以为自己多牛逼呢，**脑残**就不要当开发者了，这么简单的东西还装起来了
> > 
> > 
> > 你平时使用的源码，无论是前端后端什么语言，你安装依赖都很顺利吗？就这个项目不行吗？
> > 自己安装依赖不好不会用 npmmirror.com 吗？
> > 我们安装依赖怎么都没事，怎么就你有事呢？
> > 自己的💩没舔干净怨开发者有什么用？
> > 你安装依赖又不是从开发者的服务器
> > 你应该骂 npm 包管理工具怎么就歧视你不让你正常访问
> 
> 臭伪洋鬼子，就不要叫了，会不会用docker，npmmirror.com是你妈妈开的？可以注入依赖吗？

这个项目是 JavaScript 的，我以为你说的是 npm 镜像

但是不管怎么样，Docker 之前也不是没有中国镜像

退一万步说，我是个傻逼，没错，我妈死了，我全家死了，我承认，你完全可以认同，我不反驳



但是，这毕竟是个开源项目，你要是觉得这个是开发者需要优化的东西，你为何不优化一下并且提 Pull 请求呢？

我看了你的 GitHub 主页，在没有中看到了你的技术非常牛逼，那你就帮大家解决这个问题吧，我在 LA 膜拜一下你的代码

**Comment by BigdataZjk** [comment]
腾讯云机器，各种镜像源都试了，三个不看问题详情，看个标题就来喷，服了

**Comment by BigdataZjk** [comment]
> 中国政府干的网络审查让开发者来解决？有毛病。

伍嘉贤牛的
