### ISSUE TITLE
如何显示高级工具的隐身测试功能呢？

### ISSUE THREAD

**Issue by Suery** [jason5ng32/MyIP#227]
在 https://ipcheck.ing/ 高级工具中可以看到有一个隐身测试功能，但是下载代码部署后却发现没有该功能的显示，查看了下代码发现隐身测试的部分代码是有的，如何启用这个功能呢？
![image](https://github.com/user-attachments/assets/b130d87f-0470-4262-9937-91aece18cbcd)

**Comment by jason5ng32** [comment]
This feature is still being tested and is not yet fully developed.
