### ISSUE TITLE
Speed Test not working

### ISSUE THREAD

**Issue by sergioperezcheco** [jason5ng32/MyIP#228]
## Environment:

* Operating System:Win10
* Browser (if applicable):Edge
* Node Version:latest
* Vite Version:/
* Vue3 Version:/
* Docker Version (if applicable):27.0.3
* Deployment Method (Vercel/Docker/Node):docker
* Environment Variables (without sensitive info):/
* Any other relevant software versions:/

## Description:

Provide a clear and concise description of what the bug is.

Steps to Reproduce:

1. 点击进行网速测试
   
## Expected Behavior:

正常测试延迟及网速

## Actual Behavior:

无法测试
![4f059491d34298e5c3520.png](https://img.checo.cc/file/4f059491d34298e5c3520.png)

## Terminal & Console Logs:

**Important**: Please include the terminal logs and browser console logs if applicable. These logs are crucial for identifying the root cause of the issue.

### Terminal Logs (include any error messages or stack traces):

[Logs here]

### Browser Console Logs (if frontend issue):

[Logs here]

Additional Context:

Add any other context about the problem here, like links to related issues, logs, etc.

## Possible Solution (optional):

If you have an idea of how to fix the issue, please describe it here.

**Comment by jason5ng32** [comment]
是 @cloudflare/speedtest 的一个 bug 导致的。
试试最新的 dev 分支，有一个补丁可以缓解这个 bug。

**Comment by sergioperezcheco** [comment]
> 是 @cloudflare/speedtest 的一个 bug 导致的。 试试最新的 dev 分支，有一个补丁可以缓解这个 bug。

请问能推送到docker吗，我还是想使用docker部署

**Comment by jason5ng32** [comment]
暂时不会。如果一段时间后，CF 官方没有修复这个 bug，我会推送到正式版。这种 bug 还是应该等待官方，打补丁并不优雅。着急的话，可以通过 dev 分支的说明文档自己搞搞。

**Comment by jason5ng32** [comment]
Solved by Cloudflare.
https://github.com/cloudflare/speedtest/issues/38
