### ISSUE TITLE
[ vercel deploy failed ]

### ISSUE THREAD

**Issue by OnlyFor** [jason5ng32/MyIP#229]
i see this error in vercel when i deploy recent days:

Error: No more than 12 Serverless Functions can be added to a Deployment on the Hobby plan. Create a team (Pro plan) to deploy more. Learn More: https://vercel.link/function-count-limit

maybe some function can be set or combined mananlly in config ?

**Comment by jason5ng32** [comment]
Not planned.
I don't intend to modify the program because of the limitations of a free account for a particular platform. You can try deploying with Docker or reducing the number of scripts in the backend on your own.

**Comment by jaychoubaby** [comment]
> i see this error in vercel when i deploy recent days:
> 
> Error: No more than 12 Serverless Functions can be added to a Deployment on the Hobby plan. Create a team (Pro plan) to deploy more. Learn More: https://vercel.link/function-count-limit
> 
> maybe some function can be set or combined mananlly in config ?

你把api目录改成apis就可以部署了
