### ISSUE TITLE
Network Connectivity

### ISSUE THREAD

**Issue by HanaKDev** [jason5ng32/MyIP#235]
https://github.com/jason5ng32/MyIP/blob/44f570b1ec37cac4c53c0a619a0559ed576d254a/frontend/components/ConnectivityTest.vue#L142

Some IPs may require human verification to access https://chatgpt.com/favicon.ico, so please use https://chatgpt.com/robots.txt instead.

**Comment by jason5ng32** [comment]
It is not possible to call robots.txt for web testing, as this would run into CORS restrictions.
