### ISSUE TITLE
一个小提议

### ISSUE THREAD

**Issue by Duan-rax** [jason5ng32/MyIP#24]
在代码中，将微软地图Api的值，做成环境变量，同时可以前台隐藏。
这样的话，在vercel部署时可以后台输入，而不用更改源代码，防止key泄漏。

**Comment by jason5ng32** [comment]
我也想弄环境变量，但☝️意味着我要重构整个项目，我还不会呢…这个项目本身是我作为产品经理学 vue 的第一个项目🤣

**Comment by zhuima** [comment]
vercel 本身支持环境变量，程序里使用process.env.AZURE_MAP_API即可获取对应的值，本地开发的时候根目录添加.env，里面输入AZURE_MAP_API=xxxx, 这种即可

**Comment by jason5ng32** [comment]
我想了一下，似乎这样也不能阻止 key 泄露的问题，因为地图的 URL 里会包含 Key 的值。
是否还是应该起一个后端服务，将 API 包一下？

**Comment by zhuima** [comment]
地图的URL是临时的key吧，并不是调用地图的

**Comment by jason5ng32** [comment]
我在本地差不多弄完了，估计下周抽空弄完即可发版

**Comment by jason5ng32** [comment]
已支持环境变量。
