### ISSUE TITLE
[功能请求] User-Agent 查询

### ISSUE THREAD

**Issue by loveqianool** [jason5ng32/MyIP#241]
在高级工具加个框框显示访问设备 UA 信息？或者在其他地方显示。

**Comment by jason5ng32** [comment]
纯粹讨论：其实我一直没 get 到显示 UA 的意义，因为自己用什么浏览器，自己很清楚啊

**Comment by jason5ng32** [comment]
测试版： https://ipcheck.ing/#/browserinfo
