### ISSUE TITLE
增加对开源GeoCN的IP查询接口的支持

### ISSUE THREAD

**Issue by anunol** [jason5ng32/MyIP#242]
这个开源项目的IP API查询接口确实不错https://github.com/ljxi/GeoCN
查询的精度很高，IPV6可以精确到区县级别
希望能够支持这个项目自己部署托管的IP查询接口，默认可使用作者的api接口

**Comment by jason5ng32** [comment]
它用的是 maxmind 格式，本项目是支持 maxmind 离线数据库的，你替换成他的就行，应该兼容。

**Comment by anunol** [comment]
不是maxmind离线数据库，是请求接口，例如这种格式https://ipvx.netart.cn/?ip=222.137.1.1，IP查询接口和myip不是部署在同一台主机上面

**Comment by jason5ng32** [comment]
暂不考虑，数据库部分只考虑添加较知名公司的数据库，建议自行修改代码进行个性化定制。
