### ISSUE TITLE
请修改您网站中中国台湾省使用的旗帜图标

### ISSUE THREAD

**Issue by yrjjun** [jason5ng32/MyIP#245]
尊敬的ipcheck.ing网站开发者：
      您好！
      我注意到了您的网站中多项测试（如全球延迟测试）中的列表里的对中国台湾省地区使用的旗帜为“中华民国”的旗帜，请尊重中国主权和领土完整，世界只有一个中国，台湾同属于中国，请尊重一个中国原则，麻烦您修改为中华人民共和国国旗，谢谢

**Comment by thundernet8** [comment]
为什么要改沦陷区的旗帜呢

**Comment by mnhudbbdjxjx** [comment]
革命小将无处不在啊

**Comment by Tspm1eca** [comment]
中国原则没告诉你不要翻墙吗？

**Comment by yrjjun** [comment]
> 中国原则没告诉你不要翻墙吗？

我上个GitHub需要翻墙吗

**Comment by Tspm1eca** [comment]
> > 中国原则没告诉你不要翻墙吗？
> 
> 我上个GitHub需要翻墙吗

你确定不需要？

**Comment by yrjjun** [comment]
> > > 中国原则没告诉你不要翻墙吗？
> > 
> > 
> > 我上个GitHub需要翻墙吗
> 
> 你确定不需要？

只是慢一点，又不是打不开，不需要翻墙
