### ISSUE TITLE
Please use correct docker tags for released versions

### ISSUE THREAD

**Issue by dougmaitelli** [jason5ng32/MyIP#252]
**Is your feature request related to a problem? Please describe.**
I currently use `What's up Docker` to monitor available updates to my containers. This, like many other container update tools depends on the container sha that changes between deployments, but a neat feature is that it is capable to get the tag name from the new image and parse a version number from it, making it possible for me to have a clear view of what versions are updating and even automatically link the related changelogs on GitHub. Currently `MyIP` is always pushing every new docker image just as `latest` and does not assign any version tags to these, which makes the process I described above impossible.

Having tags per version basis is also a good practice to make it easier for people that want to pin their environments for one specific version of a project or rollback to older releases.

**Describe the solution you'd like**
I would like to propose that the deployment process of `MyIP` pushes the docker images with tags related to the actual version.

**Comment by jason5ng32** [comment]
It should work now. 
#256
