### ISSUE TITLE
集成 @vercel/analytics 

### ISSUE THREAD

**Issue by wangxin6** [jason5ng32/MyIP#26]
希望可以集成 @vercel/analytics 这样可以进行网站访问分析

https://vercel.com/docs/analytics/quickstart

https://github.com/Yidadaa/ChatGPT-Next-Web/commit/76f851bfa6ab3d5f9c310eaa78ae0e82ef938b2b

**Comment by jason5ng32** [comment]
我试过了，觉得 vercel 的分析太弱了，除了看到用户数之外，其它的数据价值太少。所以现在代码里集成了 GA 的统计。自己改一下代码里的统计 ID 就行。
