### ISSUE TITLE
Bing Maps 即将关闭

### ISSUE THREAD

**Issue by dreamsmaner** [jason5ng32/MyIP#264]
收到微软的邮件，Bing地图服务明年年中要关闭了，作者是不是要考虑把 Bing Maps API 转移了？

Reminder: Migrate from your current Bing Maps account by June 30, 2025
 
On May 21, 2024, we shared our vision for a single enterprise mapping platform on Azure and that Bing Maps for Enterprise will be retired on June 30, 2028.

What You Need to Know:
The ability to purchase Bing Maps for Enterprise SKUs and the availability of the Bing Maps for Enterprise services will end according to the following timeline: 

Customers using Bing Maps for Enterprise Basic or Free account will no longer be able to use Bing Maps for Enterprise services beyond June 30, 2025. 
Basic / Free account customers who would like to continue using enterprise maps from Microsoft are encouraged to move to Azure Maps before June 30, 2025. 
Existing Basic / Free account customers who would like to continue using Bing Maps for Enterprise until the service end date of June 30, 2028 can upgrade to a paid Enterprise License by contacting [maplicq@microsoft.com](mailto:maplicq@microsoft.com) before June 30, 2025.

Next steps:
We are asking existing Bing Maps for Enterprise Basic / Free customers to migrate to Azure Maps before June 30th, 2025.

We have created a range of on demand webinars to help you migrate.

**Comment by jason5ng32** [comment]
看起来还有半年时间？

**Comment by dreamsmaner** [comment]
今天刚收到的邮件，满打满算7个月不到。

**Comment by jason5ng32** [comment]
我也收到了。
从可用的免费额度来看，看起来得换 Google 了。

**Comment by jason5ng32** [comment]
#265
