### ISSUE TITLE
actions 自动同步上游代码功能

### ISSUE THREAD

**Issue by wangxin6** [jason5ng32/MyIP#27]
希望可以有 actions 自动同步上游代码功能

https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/blob/main/.github/workflows/sync.yml
https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/blob/main/README_CN.md#保持更新

**Comment by jason5ng32** [comment]
哥们，你这是逼着一个产品经理逐渐变成程序员啊

**Comment by jason5ng32** [comment]
去试试吧。
