### ISSUE TITLE
IP数据不显示详细信息

### ISSUE THREAD

**Issue by lxr760** [jason5ng32/MyIP#3]
如图，只有IP地址那里有数据，下面的国家、地区、城市、ISP、ASN都是空白

![image](https://github.com/jason5ng32/MyIP/assets/8476457/6d375bdd-50d9-4be3-a748-150b24220907)

**Comment by jason5ng32** [comment]
大概率是因为你当前的 IP 查询数据次数过多了，可以试试不挂代理裸奔看看，或者换一个代理看看。

**Comment by jason5ng32** [comment]
还有一种可能是你的广告屏蔽插件屏蔽了查询请求。
