### ISSUE TITLE
3.1问题:

### ISSUE THREAD

**Issue by Luci8109** [jason5ng32/MyIP#38]
已填写IPINFO_API_TOKEN
IP信息内无法显示IP内容
![Screenshot_2024-01-31-08-29-02-023_com android chrome-edit](https://github.com/jason5ng32/MyIP/assets/94164803/c2fb6a53-1b0f-41d6-b3a7-252456b73e0f)

**Comment by jason5ng32** [comment]
Please report bugs with issure template.
