### ISSUE TITLE
建议添加可以vercel上一键傻瓜式部署的说明

### ISSUE THREAD

**Issue by hidenmaskvip** [jason5ng32/MyIP#5]
大佬，你的这个项目可以在vercel上一键傻瓜式部署，建议专门说明；同时建议针对vercel进行专门的小修改，例如能够通过vercel添加环境变量

**Comment by jason5ng32** [comment]
行。在说明文档里加了个 Vercel 按钮。
另外，因为这是纯前端的项目，我不打算（主要是不会）弄后端的部分，所以不搞环境变量啦。
