### ISSUE TITLE
Feature request: Adding IPinfo to the homepage and adding support for tokenless access

### ISSUE THREAD

**Issue by abdullahdevrel** [jason5ng32/MyIP#53]
I work for IPinfo, and I appreciate the inclusion of IPinfo.io in the project. However, I noticed that IPinfo is not shown on the homepage of https://ipcheck.ing/. MyIP is one of the most fantastic services that supports our service, so we would be grateful if the project shows our data to all its users.

![image](https://github.com/jason5ng32/MyIP/assets/111275753/beec3509-ce81-4e1b-bd24-0814e4bb6065)

**Is your feature request related to a problem? Please describe.**

I would like to request the addition of IPinfo on the homepage.

Another aspect I would like to request is the addition of IPinfo's tokenless access to the project and site. IPinfo supports tokenless access to its API endpoint and can deliver up to 1,000 requests per day.

We appreciate the support for adding the access token, and I think users should be able to chose to provide a token or not. We would like to ensure that all users of MyIP have access to our data, regardless of whether they have an account with us or not. Please do keep the access token input system, but if the user has not provided an access token, I hope they can still get data from us.

IPinfo also supports IPv6 connection through the following API endpoint:

```
https://v6.ipinfo.io
```

**Describe the solution you'd like**

I would to like request the following:

- Adding IPinfo in the homepage of `https://ipcheck.ing/`
- Adding support for tokenless access to IPinfo's API service.
- Adding support for the IPv6 endpoint

**Describe alternatives you've considered**

I have not considered any alternatives.

**Additional context**

None.

**Comment by jason5ng32** [comment]
Hi Abdullah,

IPInfo has high accuracy, I like it. This is why it is placed in the first place of the request order.

The **Sources** you see on the page is not the source of IP geolocation data, but the sources of getting user's IP address. The logic of MyIP is to get the IP from some services first, and then call the IP geolocation data service including IPInfo to get the IP geolocation data.

I didn't notice that IPInfo provides tokenless API before. I have updated the code and supported tokenless calls.

**Comment by abdullahdevrel** [comment]
> IPInfo has high accuracy, I like it. This is why it is placed in the first place of the request order.

Thank you very much, Jason. We are thrilled to hear such praise from the maintainer of such a popular project.

> The Sources you see on the page is not the source of IP geolocation data, but the sources of getting user's IP address. 

Ahhh... I looked at the network traffic for https://ipcheck.ing/ and I noticed that only public IP addresses are being returned. I got a bit confused.

![image](https://github.com/jason5ng32/MyIP/assets/111275753/aa2aff6f-596e-4414-ad9f-f9884a8d91c1)

I expected the call to be made on the frontend and get the IP geolocation information in a single call. I should have looked into the source that was directly in front of me!

> I didn't notice that IPInfo provides tokenless API before. I have updated the code and supported tokenless calls.

Thank you very much; that is why I am here. :)

I am closing the issue, as you have merged: https://github.com/jason5ng32/MyIP/pull/54

**Comment by jason5ng32** [comment]
@abdullahdevrel 
Does IPinfo.io has free quota of Privacy Detection API? I look for the website and it seems that there's no free quota for Privacy Detection API, is that correct?

It would be great if you could provide some, and then I can add it to this open-source project.

**Comment by abdullahdevrel** [comment]
Hey @jason5ng32 I am sorry for the late reply. Unfortunately, we don't have a free quota for the privacy detection API service. If that ever changes, I will reach out to you.
