### ISSUE TITLE
增加功能 : 自建服务时可修改的页面标题

### ISSUE THREAD

**Issue by lsdxfs** [jason5ng32/MyIP#95]
![图片](https://github.com/jason5ng32/MyIP/assets/115888450/ea0cedb1-0f24-4618-a581-8517a7f5b1e0)

在自建服务的情况下网页的标题还是会显示 IPCheck.ing 的域名 

建议添加相关环境变量 可自定义标题 ❤️

**Comment by jason5ng32** [comment]
自己改一下代码？
